package com.cems.service.impl;

import com.cems.entity.Event;
import com.cems.entity.Registration;
import com.cems.exception.BadRequestException;
import com.cems.service.PdfService;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import org.springframework.stereotype.Service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class PdfServiceImpl implements PdfService {

    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("MMM dd, yyyy - hh:mm a");
    private static final DeviceRgb PRIMARY_COLOR = new DeviceRgb(79, 70, 229); // Indigo 600
    private static final DeviceRgb LIGHT_BG = new DeviceRgb(243, 244, 246);

    @Override
    public ByteArrayInputStream generateAttendeeRosterPdf(Event event, List<Registration> registrations) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter writer = new PdfWriter(out);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf, PageSize.A4);
            document.setMargins(36, 36, 36, 36);

            // Header Title
            Paragraph title = new Paragraph("COLLEGE EVENT ATTENDEE ROSTER")
                    .setFontSize(18)
                    .setBold()
                    .setFontColor(PRIMARY_COLOR)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(15);
            document.add(title);

            // Event Details Box
            Table detailsTable = new Table(UnitValue.createPercentArray(new float[]{30, 70})).useAllAvailableWidth();
            detailsTable.addCell(createHeaderCell("Event Title:"));
            detailsTable.addCell(createValueCell(event.getTitle()));
            detailsTable.addCell(createHeaderCell("Category:"));
            detailsTable.addCell(createValueCell(event.getCategory() != null ? event.getCategory() : "N/A"));
            detailsTable.addCell(createHeaderCell("Venue:"));
            detailsTable.addCell(createValueCell(event.getVenue() != null ? event.getVenue().getName() : "N/A"));
            detailsTable.addCell(createHeaderCell("Start Time:"));
            detailsTable.addCell(createValueCell(event.getStartTime() != null ? event.getStartTime().format(DATE_FORMATTER) : "N/A"));
            detailsTable.addCell(createHeaderCell("Organizer:"));
            detailsTable.addCell(createValueCell(event.getOrganizer() != null ? event.getOrganizer().getFullName() : "N/A"));
            detailsTable.addCell(createHeaderCell("Total Registrations:"));
            detailsTable.addCell(createValueCell(String.valueOf(registrations.size())));

            document.add(detailsTable);
            document.add(new Paragraph("\n"));

            // Attendee Table
            Table table = new Table(UnitValue.createPercentArray(new float[]{10, 25, 30, 20, 15})).useAllAvailableWidth();
            table.addHeaderCell(createTableHeader("#"));
            table.addHeaderCell(createTableHeader("Student Name"));
            table.addHeaderCell(createTableHeader("Email"));
            table.addHeaderCell(createTableHeader("Status"));
            table.addHeaderCell(createTableHeader("Checked In"));

            int count = 1;
            for (Registration reg : registrations) {
                table.addCell(new Cell().add(new Paragraph(String.valueOf(count++)).setFontSize(9)));
                table.addCell(new Cell().add(new Paragraph(reg.getStudent() != null ? reg.getStudent().getFullName() : "Unknown").setFontSize(9)));
                table.addCell(new Cell().add(new Paragraph(reg.getStudent() != null ? reg.getStudent().getEmail() : "N/A").setFontSize(9)));
                table.addCell(new Cell().add(new Paragraph(reg.getStatus().name()).setFontSize(9)));
                table.addCell(new Cell().add(new Paragraph(reg.getCheckedInAt() != null ? "Yes" : "No").setFontSize(9)));
            }

            document.add(table);

            // Footer
            Paragraph footer = new Paragraph("Generated by College Event Management System (CEMS)")
                    .setFontSize(8)
                    .setFontColor(ColorConstants.GRAY)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(20);
            document.add(footer);

            document.close();
        } catch (Exception e) {
            throw new BadRequestException("Failed to generate PDF: " + e.getMessage());
        }

        return new ByteArrayInputStream(out.toByteArray());
    }

    @Override
    public ByteArrayInputStream generateRegistrationTicketPdf(Registration registration) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Event event = registration.getEvent();

        try {
            PdfWriter writer = new PdfWriter(out);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf, PageSize.A5);
            document.setMargins(30, 30, 30, 30);

            // Header Banner
            Paragraph title = new Paragraph("EVENT ENTRY PASS / TICKET")
                    .setFontSize(16)
                    .setBold()
                    .setFontColor(PRIMARY_COLOR)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(10);
            document.add(title);

            Paragraph ticketCode = new Paragraph("PASS CODE: CEMS-REG-" + registration.getId())
                    .setFontSize(10)
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(15);
            document.add(ticketCode);

            // Event & Student Details Table
            Table table = new Table(UnitValue.createPercentArray(new float[]{35, 65})).useAllAvailableWidth();

            table.addCell(createHeaderCell("Event Name:"));
            table.addCell(createValueCell(event.getTitle()));

            table.addCell(createHeaderCell("Category:"));
            table.addCell(createValueCell(event.getCategory() != null ? event.getCategory() : "N/A"));

            table.addCell(createHeaderCell("Venue / Location:"));
            table.addCell(createValueCell(event.getVenue() != null ? event.getVenue().getName() + " (" + event.getVenue().getLocation() + ")" : "N/A"));

            table.addCell(createHeaderCell("Date & Time:"));
            table.addCell(createValueCell(event.getStartTime().format(DATE_FORMATTER)));

            table.addCell(createHeaderCell("Attendee Name:"));
            table.addCell(createValueCell(registration.getStudent().getFullName()));

            table.addCell(createHeaderCell("Attendee Email:"));
            table.addCell(createValueCell(registration.getStudent().getEmail()));

            table.addCell(createHeaderCell("Department:"));
            table.addCell(createValueCell(registration.getStudent().getDepartment() != null ? registration.getStudent().getDepartment() : "General"));

            table.addCell(createHeaderCell("Registration Status:"));
            table.addCell(createValueCell(registration.getStatus().name()));

            table.addCell(createHeaderCell("Registration Time:"));
            table.addCell(createValueCell(registration.getRegisteredAt() != null ? registration.getRegisteredAt().format(DATE_FORMATTER) : "N/A"));

            document.add(table);

            Paragraph instructions = new Paragraph("\n* Please present this ticket at the event entrance for QR / Check-In verification.")
                    .setFontSize(8)
                    .setFontColor(ColorConstants.DARK_GRAY)
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginTop(15);
            document.add(instructions);

            document.close();
        } catch (Exception e) {
            throw new BadRequestException("Failed to generate registration ticket PDF: " + e.getMessage());
        }

        return new ByteArrayInputStream(out.toByteArray());
    }

    private Cell createHeaderCell(String text) {
        return new Cell().add(new Paragraph(text).setBold().setFontSize(9)).setBackgroundColor(LIGHT_BG);
    }

    private Cell createValueCell(String text) {
        return new Cell().add(new Paragraph(text != null ? text : "").setFontSize(9));
    }

    private Cell createTableHeader(String text) {
        return new Cell().add(new Paragraph(text).setBold().setFontSize(9).setFontColor(ColorConstants.WHITE)).setBackgroundColor(PRIMARY_COLOR);
    }
}
